### ISSUE TITLE
Change Label Legend

### ISSUE THREAD

**Issue by alicarlos** [python-windrose/windrose#103]
Be able to change the labels on the bins

![onspw](https://user-images.githubusercontent.com/44268113/47166008-3e488680-d2c9-11e8-9f75-331511994759.png)

**Comment by scls19fr** [comment]
https://github.com/python-windrose/windrose/blob/master/windrose/windrose.py#L222-L248

**Comment by ocefpaf** [comment]
Should be fixed by https://github.com/python-windrose/windrose/pull/146 and we can also override that using mpl like in https://github.com/python-windrose/windrose/pull/120#issuecomment-1253717780.
