### ISSUE TITLE
A quick clarification question

### ISSUE THREAD

**Issue by winash12** [python-windrose/windrose#112]
I just made my first windrose plot using your software and I am extremely grateful.

https://imgur.com/a/pa1q8pW

Just had a couple of questions about the software.

1) The various frequencies - they do not have to add up to 100 right ?

2) is there a way to superpose this image on Google Earth ?

**Comment by winash12** [comment]
`from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np

ws = np.array([0,0,0,1.1,0,0.7,0.8,2.7,3,0.4,1.3,0.4,1,0,0.9,1.6,0,0,0.3,1.5,0.1,1,0.6,0,0.2,1,0.5,0.6,0.2,0,1.1])

print(ws.shape)

wd = np.array([359.2,359.2,359.2,132,359.2,334.8,332.8,81.1,81.1,109,135.9,103.1,147.1,359.2,306,320.1,359.2,359.2,177.9,12.2,350,8.8,344.1,359.2,204.8,117.8,93.8,148.1,230.2,359.2,162.8])

print(wd.shape)


ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()


plt.savefig('windrose.png')`

**Comment by ocefpaf** [comment]
> 1. The various frequencies - they do not have to add up to 100 right ?

Not sure what you mean. Are you referring to the bins? You can specify those if you want to.

> 2\. is there a way to superpose this image on Google Earth ?

This is beyond the scope of this library but you can overlay a png on GE with one of the many GE libraries that exists out there, or write the kml manually. BTW, check the map overlay in our docs in case you want a static map.

Closing this but please re-open if you have more questions.
