### ISSUE TITLE
windrose deprecated function which cannot work with python3.6.2 and newest matplotlib?

### ISSUE THREAD

**Issue by JoeLeung2018** [python-windrose/windrose#117]
I am using the following codes to call windrose.py:

```python
from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np

ws = np.random.random(500) * 6
wd = np.random.random(500) * 360

ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()
```
The following is some messages of those deprecated function :
```
The Appender class was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  addendum = docstring.Appender(msg, "\n\n")
C:\python36\lib\site-packages\windrose\windrose.py:30: MatplotlibDeprecationWarning:
The copy_dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use docstring.copy() and cbook.dedent() instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
C:\python36\lib\site-packages\windrose\windrose.py:30: MatplotlibDeprecationWarning:
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.getdoc() instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
C:\python36\lib\site-packages\windrose\windrose.py:30: MatplotlibDeprecationWarning:
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.cleandoc instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
```
What's wrong and How can I fix the problem? 
Thanks for your kindness and reply.

**Comment by scls19fr** [comment]
https://github.com/python-windrose/windrose/pull/83 (by @weber-s ) added the use of `docstring.Appender` maybe he can have a look

**Comment by JoeLeung2018** [comment]
The following is part of the winrose.py:

def _autogen_docstring(base):
    """Autogenerated wrappers will get their docstring from a base function
    with an addendum."""
    # msg = "\n\nAdditional kwargs: hold = [True|False] overrides default hold state"
    msg = ""
    addendum = docstring.Appender(msg, "\n\n")
    return lambda func: addendum(docstring.copy_dedent(base)(func))

docstring.Appender and copy_dedent are all deprecated ?

**Comment by JoeLeung2018** [comment]
The following is part of the winrose.py:

def _autogen_docstring(base):
    """Autogenerated wrappers will get their docstring from a base function
    with an addendum."""
    # msg = "\n\nAdditional kwargs: hold = [True|False] overrides default hold state"
    msg = ""
    addendum = docstring.Appender(msg, "\n\n")
    return lambda func: addendum(docstring.copy_dedent(base)(func))

docstring.Appender and copy_dedent are all deprecated ?

**Comment by scls19fr** [comment]
Please use triple triple backticks ``` 
when pasting code (see my edit)
https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by JoeLeung2018** [comment]
'''
def _autogen_docstring(base):
    """Autogenerated wrappers will get their docstring from a base function
    with an addendum."""
    # msg = "\n\nAdditional kwargs: hold = [True|False] overrides default hold state"
    msg = ""
    addendum = docstring.Appender(msg, "\n\n")
    return lambda func: addendum(docstring.copy_dedent(base)(func))

'''
docstring.Appender and copy_dedent are all deprecated ?

**Comment by JoeLeung2018** [comment]
```
    fdasfdasf
```

**Comment by JoeLeung2018** [comment]
Thanks for the triple backticks:
```
def _autogen_docstring(base):
    """Autogenerated wrappers will get their docstring from a base function
    with an addendum."""
    # msg = "\n\nAdditional kwargs: hold = [True|False] overrides default hold state"
    msg = ""
    addendum = docstring.Appender(msg, "\n\n")
    return lambda func: addendum(docstring.copy_dedent(base)(func))
```

docstring.Appender and copy_dedent are all deprecated ?

**Comment by JoeLeung2018** [comment]
The following is part of the winrose.py:

```
def _autogen_docstring(base):
    """Autogenerated wrappers will get their docstring from a base function
    with an addendum."""
    # msg = "\n\nAdditional kwargs: hold = [True|False] overrides default hold state"
    msg = ""
    addendum = docstring.Appender(msg, "\n\n")
    return lambda func: addendum(docstring.copy_dedent(base)(func))
```
docstring.Appender and copy_dedent are all deprecated ?

**Comment by JoeLeung2018** [comment]
The problem is still there and I don't know how to solve it .

**Comment by JoeLeung2018** [comment]
please visit  https://github.com/python-windrose/windrose/blob/master/windrose/windrose.py
```
def _autogen_docstring(base):
    """Autogenerated wrappers will get their docstring from a base function
    with an addendum."""
    # msg = "\n\nAdditional kwargs: hold = [True|False] overrides default hold state"
    msg = ""
    addendum = docstring.Appender(msg, "\n\n")
    return lambda func: addendum(docstring.copy_dedent(base)(func))
```

docstring.Appender and copy_dedent are all deprecated ?

**Comment by weber-s** [comment]
Hei!

Should be fixed now in the PR.

**Comment by scls19fr** [comment]
Thanks to PR https://github.com/python-windrose/windrose/pull/118 from @weber-s this issue have been fixed.
@JoeLeung2018 could you give it a try to latest development version?
see https://github.com/python-windrose/windrose#install-latest-development-version for install

**Comment by AndyLuckert** [comment]
The compatibility issue between matplotlib and windrose **came back as error** related to `AttributeError: module 'matplotlib.docstring' has no attribute 'Appender'`.

I've already commented on the prematurely closed issue:
https://github.com/python-windrose/windrose/issues/119#issuecomment-661115579
