### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by scls19fr** [python-windrose/windrose#127]
Hello,

just a few words to tell python-windrose contributors that windrose is cited in the following paper.

Daniel Fosas, Francis Moran, Sukumar Natarajan, John Orr & David Coley (2019) The importance of thermal modelling and prototyping in shelter design, Building Research & Information, DOI: https://www.tandfonline.com/doi/full/10.1080/09613218.2019.1691489

Kind regards

**Comment by ocefpaf** [comment]
@scls19fr this is in the README now. Maybe we can close this/
