### ISSUE TITLE
Color-coding directions.

### ISSUE THREAD

**Issue by mindey** [python-windrose/windrose#133]
I'd like to have the wind rose diagram with color-coding for directions, i.e., a bit like:

![](https://avatars0.githubusercontent.com/u/66762092?s=400&u=9ee6b85fcd2b401bdd48f7d500160f0a76496f5b&v=4)

so that we can have a different color per direction, and ideally, colors fusing like rainbow, via fade-in-fade-out like effect between them.

This is already possible? (If so, sorry for not looking deeper. If not, how do you think it would be best to implement such feature?)

**Comment by dancergraham** [comment]
Hello,
Do you have a specific use case for this?  I think you might need to use a different plotting tool - it sounds like it is out of scope for this library - wind roses are usually colored by speed.

**Comment by mindey** [comment]
@dancergraham yes, I'd like to color [dimensions of happiness](https://0oo.li/method/955/dimensions-of-happiness), check out [this video](https://youtu.be/LaKtTlj75HM?t=27). ;)

**Comment by ocefpaf** [comment]
> it sounds like it is out of scope for this library - wind roses are usually colored by speed.

Indeed. Take a look at https://github.com/alfonsosemeraro/pyplutchik, seems to be what you need.
