### ISSUE TITLE
Dedent function is deprecated 

### ISSUE THREAD

**Issue by GeoffreyJohnen** [python-windrose/windrose#135]
Hi,

It seems I can't use the windrose package because of : 
EDIT : I can use it totally fine, but I have a warning.

"The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.cleandoc instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))"

I am using python 3.8.3 with the following libraries : 

atomicwrites==1.4.0
attrs==19.3.0
colorama==0.4.3
configparser==5.0.0
cycler==0.10.0
kiwisolver==1.2.0
matplotlib==3.2.2
more-itertools==8.4.0
numpy==1.19.0
packaging==20.4
pandas==1.0.5
pluggy==0.13.1
py==1.9.0
pyparsing==2.4.7
pytest==5.4.3
python-dateutil==2.8.1
pytz==2020.1
six==1.15.0
wcwidth==0.2.5
windrose==1.6.7

**Comment by dancergraham** [comment]
https://github.com/python-windrose/windrose/issues/136#issuecomment-662042174

**Comment by weber-s** [comment]
Hello,

I should be fixed with the latest pypi version:

```
pip3 install windrose --upgrade
```
