### ISSUE TITLE
Tag/release v1.6.8 ?

### ISSUE THREAD

**Issue by weber-s** [python-windrose/windrose#142]
To my understanding, package is build and uploaded to pypi based on new tag.

I don't have direct write access to this repo, so I can't push tags or manually create one. I would be nice to 

```
git tag v1.6.8
git push --tags
```

in order to have the build on pypi.

**Comment by scls19fr** [comment]
@weber-s you have been granted write access to this repo.
If you need something else, just ask.

**Comment by weber-s** [comment]
Thank you very much! I just pushed the new tag. Hope it works :)
