### ISSUE TITLE
Map Projection/Labels Not Correct

### ISSUE THREAD

**Issue by fgroff** [python-windrose/windrose#147]
I was following your tutorial (https://windrose.readthedocs.io/en/latest/usage.html) line by line, and I do not have the same direction labels (see figure 1). 
![Figure_1](https://user-images.githubusercontent.com/40182667/95524515-d5171d80-098e-11eb-9296-51da8d675619.png)

I did another check w/ fake data, and as you can see in Figure_2, the labels are off by 90 degrees:

ws = np.array([1,1,1,10,10,10])
wd = np.array([80,90,100,260,270,280]) 

ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()
![Figure_2](https://user-images.githubusercontent.com/40182667/95524654-2d4e1f80-098f-11eb-9e60-338e88042bcb.png)

While plotted in the correct quadrant, the labelling is off by 90 degrees and the "N, NE, E..." text labels are missing. It is also no longer increasing in degrees going clockwise. It seems to have defaulted back to basic matplotlib polar projection settings.

**Comment by beninie** [comment]
I encountered the same problem yesterday. Sorry to say that I have not yet found a solution, hopefully someone find a way to fix this.

**Comment by fgroff** [comment]
My "solution" was to override the labels.

coordinates = ('E','NE','N','NW','W','SW','S','SE')
ax.set_xticklabels(coordinates)

Definitely doesn't make me feel great, but I did a lot of checks and the
data seems to be plotting in the right spaces and in the right direction,
so that was my intermittent fix.

**Comment by domja-bas** [comment]
You should be able to get around this temporarily through the following:
`ax = WindroseAxes.from_ax(theta_labels=["E", "N-E", "N", "N-W", "W", "S-W", "S", "S-E"])` although it looks like the maintainers have already created a branch to fix this particular issue. Shouldn't be long now!

**Comment by ocefpaf** [comment]
This was fixed in https://github.com/python-windrose/windrose/issues/165

Please open a new issue if this resurfaces.
