### ISSUE TITLE
length of wind direction not equal to wind speed.

### ISSUE THREAD

**Issue by dmilstea** [python-windrose/windrose#150]
I am so glad that someone has provided this package.  I need some help understanding how to use it though.
I get an error that the wind direction and wind speed need to be equal lengths.
This is my data:
wind directions are every 10 degrees.  36 wind directions 0-360
I have 11 bins of wind speed for each wind direction.
Data:
```
Direction,1-4 kts,5-9 kts,10-14 kts,15-19 kts,20-24 kts,25-29 kts,30-34 kts,35-39 kts,40-44 kts,45-49 kts,>=50 kts,
0,1.78,1.43,0.11,0.11,0.03,0,,,,,,
10,1.81,1.58,0.09,0.11,0.01,,,,,,,
.
350,1.2,1.12,0.07,0.12,0.04,0.01,,,,,,
```
In your package, the wd and ws are 1 dimensional numpy arrays, so I put the wind directions in the 'wd' array and all of the wind speeds in the 'ws' array
and use this:
```
ax = windrose.WindroseAxes.from_ax()
ax.bar(wd, ws, bins=11, nsector=36, normed=True, opening=0.8, edgecolor='white')
```
Any advice on what to do with the data would be greatly appreciated.

**Comment by ocefpaf** [comment]
Looks like your data is already binned. I don't think we support that. If you have continuous data then you can use windrose.

Closing this but if you figure something out please post if here for others that may follow.
