### ISSUE TITLE
ModuleNotFoundError: No module named 'windroses'

### ISSUE THREAD

**Issue by garimss** [python-windrose/windrose#154]
I am getting this error. How to solve this

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-11fd51b7e933> in <module>
      1 import matplotlib.pyplot as plt
      2 import matplotlib.cm as cm
----> 3 from windroses import WindroseAxes

ModuleNotFoundError: No module named 'windroses'

Requirement already satisfied: windrose in c:\users\garima\.conda\envs\project1\lib\site-packages (1.6.8)
Requirement already satisfied: matplotlib in c:\users\garima\.conda\envs\project1\lib\site-packages (from windrose) (3.3.4)
Requirement already satisfied: numpy in c:\users\garima\.conda\envs\project1\lib\site-packages (from windrose) (1.19.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\garima\.conda\envs\project1\lib\site-packages (from matplotlib->windrose) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\garima\.conda\envs\project1\lib\site-packages (from matplotlib->windrose) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\garima\.conda\envs\project1\lib\site-packages (from matplotlib->windrose) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\garima\.conda\envs\project1\lib\site-packages (from matplotlib->windrose) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\garima\.conda\envs\project1\lib\site-packages (from matplotlib->windrose) (8.2.0)
Requirement already satisfied: six in c:\users\garima\.conda\envs\project1\lib\site-packages (from cycler>=0.10->matplotlib->windrose) (1.14.0)

**Comment by scls19fr** [comment]
Hi,

windroses is not windrose

Hope that helps

**Comment by garimss** [comment]
still same

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-e88298a8ba3d> in <module>
      1 import matplotlib.pyplot as plt
      2 import matplotlib.cm as cm
----> 3 from windrose import WindroseAxes

ModuleNotFoundError: No module named 'windrose'
