### ISSUE TITLE
Connecting windrose with wrf-python?

### ISSUE THREAD

**Issue by AndresSepulveda** [python-windrose/windrose#160]
Hi, I would like to plot a windrose from a WRF output file. Has anyone a sample code available?

This is what I've adapted so far....

`import numpy as np
import pandas as pd
import wrf 
from netCDF4 import Dataset
from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm

nc_file = Dataset("wrfout_d01_2021-09-22_00:00:00")

ws_all = wrf.getvar(nc_file, "wspd",timeidx=wrf.ALL_TIMES)
wd_all = wrf.getvar(nc_file, "wdir",timeidx=wrf.ALL_TIMES)

lat = -37.0
lon = -72.0

(x, y) = wrf.ll_to_xy(nc_file, lat, lon)
wrf.xy_to_ll(nc_file, x, y)

ws = ws_all[:, y, x]
wd = wd_all[:, y, x]

ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()

#plt.show()
plt.savefig('WindRose_WRF.png')`

Thanks,

 Andrés

**Comment by ocefpaf** [comment]
As long as you can load the wd and ws are arrays you are on the right path. Not sure if you have an specific questions, so closing this. Feel free to re-open if you have any bugs to report.
