### ISSUE TITLE
Why isn't 0 degrees due north

### ISSUE THREAD

**Issue by PhilosopherZ** [python-windrose/windrose#170]
Why isn't 0 degrees due north? Why is it not rotating clockwise?

**Comment by boeske** [comment]
I just ran into the same problem.
0° is in fact North, 90° east and so on.

However the labeling of the axis does not work.
In the first example given in the README the labels read N, N-E, and so on (see https://github.com/python-windrose/windrose/blob/master/docs/screenshots/bar.png).
My modified version of the code looks like this:
`from windrose import WindroseAxes
import matplotlib
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np

matplotlib.use('Agg')

ws = np.random.random(500) * 6
wd = np.random.random(500) * 360

wd[200:450] = 0.

ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()

plt.savefig('windrose.png',dpi=300)`

and the output looks like thi
![windrose](https://user-images.githubusercontent.com/11378200/152360564-109a63ae-bad5-47fd-8064-2ac9e3c8f857.png)
s

**Comment by 15b3** [comment]
I think your windorose version is v1.6.8.
`WindroseAxes.from_ax()` of v1.6.8 has a bug about label. See #165.

Workaround:
```
ax = WindroseAxes.from_ax(theta_labels=["E", "N-E", "N", "N-W", "W", "S-W", "S", "S-E"])
```

**Comment by ocefpaf** [comment]
This bug was fixed in https://github.com/python-windrose/windrose/pull/166

I'm preparing a new release soon.

**Comment by PhilosopherZ** [comment]
你好，我已收到你的邮件。
