### ISSUE TITLE
Support for multiple plots missing

### ISSUE THREAD

**Issue by cnske** [python-windrose/windrose#172]
Windrose's bar and contour methods return None, unlike matplotlib's bar and countor methods.

_Originally posted by @15b3 in https://github.com/python-windrose/windrose/issues/171#issuecomment-1066085172_

**Comment by ocefpaf** [comment]
Indeed. In a way we should mimic mpl but I'm not sure that is possible given the current implementation. I'm closing this as but if you have an idea please send a PR!
