### ISSUE TITLE
Wind Rose from frequency table

### ISSUE THREAD

**Issue by ali-cole** [python-windrose/windrose#189]
2 issues have been raised for this problem with no solutions yet, and I've now run into the same thing. 
[first issue link](https://github.com/python-windrose/windrose/issues/71), [second issue link](https://github.com/python-windrose/windrose/issues/169)

I need to plot a wind rose from a frequency table, so I would like the option to define wind directions and a table instead of wind directions and variables. I have dug into the source code, but I cannot sort out the right place to do this. Has anyone sorted this out or is this in development? I use this package frequently and would like to be able to continue to use it so that my wind roses remain consistent.

**Comment by ocefpaf** [comment]
@ali-cole let's close this one as duplicate and, if you don't mind, please add your comment above to the original issue. That should help future devs to address this problem.
