### ISSUE TITLE
pacman-shaped wind roses

### ISSUE THREAD

**Issue by NRaillard** [python-windrose/windrose#190]
Hello, and first of all thanks for this great package.

I have installed the latest version and have some issues that I have not encountered before: the roses are not closed, and looks like a pacman, as it can be seen from the figure enclosed below.

```{python}
import windrose as wrose
ax = wrose.WindroseAxes.from_ax()
```
![image](https://user-images.githubusercontent.com/61309853/190976763-be56224a-fc38-4121-881d-2d74b2d39912.png)

I show here a very simple plot, but the problem remains whenever I add some data.

Do you have any idea where does this problem comes from and how could I solve it ?

The following version are installed in a dedicated environment

> windrose             1.7.0
> matplotlib           3.6.0

**Comment by ocefpaf** [comment]
Looks like a problem with latest matplotlib. I can reproduce it with 3.6.0 but not with 3.5.3.

**Comment by ocefpaf** [comment]
@dopplershift and @tacaswell do you any advice for us here? I'm reading the changelog and I could not find anything that could be the cause of this changed. The expected output (here using mpl 3.5.3) is:

![Screenshot from 2022-09-19 08-33-25](https://user-images.githubusercontent.com/950575/191008315-d98abe01-4914-40a4-b8fc-b1424d30ff34.png)

**Comment by ocefpaf** [comment]
Found  it. PR https://github.com/matplotlib/matplotlib/pull/22802 removed `cla` and we should use `clear` instead. PR inbound...

**Comment by NRaillard** [comment]
I'm impressed by your reactivity... Thanks !

**Comment by ocefpaf** [comment]
> I'm impressed by your reactivity... Thanks !

OSS is more about luck than anything. I have to write some reports this week, which means I'll be procrastinating a lot and choosing "side quests" as much as I can to avoid writing :stuck_out_tongue_closed_eyes:

**Comment by ocefpaf** [comment]
> Sorry I missed this. we also had this problem with cartopy which ended up version gating if they defined `clear` or `cla`.

We are a much smaller project than cartopy and easier to just fix and release a new version ;-p
