### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by ocefpaf** [python-windrose/windrose#195]
@scls19fr what do you think? `main` is the new default on GitHub and it would make it easier for newcomers to contribute to OSS b/c the new docs all will refer to main instead of `master`.

**Comment by scls19fr** [comment]
I'm aware that master shouldn't be used anymore in such a context
https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main
So I'm ok to rename it to main.

**Comment by ocefpaf** [comment]
Done! Thanks!!
