### ISSUE TITLE
How does one names of directions such as N, NE W instead of numbers such as 0, 90 etc ? 

### ISSUE THREAD

**Issue by winash12** [python-windrose/windrose#209]
![windrose](https://user-images.githubusercontent.com/9129700/203227323-33a518ca-8a56-451c-9c3d-1f1b6fe1aa90.png)

In my code I want to plot names of direction along the windrose instead of 0, 90, 180 or 270. How can I do that ? 

`ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()`

**Comment by ocefpaf** [comment]
You can customize that with `theta_labels` or edit it `ax.set_xticklabels` after you created the `ax` object.
