### ISSUE TITLE
Incompatibility with numpy 2.0.0

### ISSUE THREAD

**Issue by SchmJo** [python-windrose/windrose#271]
Numpy 2.0.0 has recently been released, and the `windrose` package seems to be incompatible. When using it, I get the error
```console
  File "/home/.../python3.11/site-packages/windrose/windrose.py", line 10, in <module>
    from numpy.lib.twodim_base import histogram2d
ModuleNotFoundError: No module named 'numpy.lib.twodim_base'
```

To my understanding, the [histogram2d](https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html) can now be imported from `numpy` directly. When changing the troubling line to 
```python
from numpy import histogram2d
```
my code runs fine again without errors.

Related issue: FraunhoferIWES/foxes#43

Thanks for addressing this!

**Comment by ocefpaf** [comment]
I'll issue a new release with this fix. Thanks!

**Comment by SchmJo** [comment]
Thanks a lot for your quick resonse! 👍
