### ISSUE TITLE
custom binning of wind direction direction

### ISSUE THREAD

**Issue by vimalaathythan-v2w** [python-windrose/windrose#273]
Use case: need to bin the wind direction the binning interval is 10 degree. so for 360 degree we will have 36 bars . how to set the no of bars in the wind rose? 
1. I read the wind rose documentation. but could not find a parameter to define the no bins for wind direction.
2.  adjusted_wd = np.where(wd < 0, wd + 360, wd)  # Adjust negative angles to be positive
ax.bar(adjusted_wd, ws, bins=np.arange(0, 361, 10), normed=True, opening=0.8, edgecolor='white')
I modified the  bin parameter which bins the wind speed not wind direction.
Any experts here can help me?

**Comment by jkittner** [comment]
You need to set `nsector=36` as shown in this example in the documentation: https://python-windrose.github.io/windrose/usage-output.html#...or-without-filled-regions using `nsector=16`.

It is also listed under "Optional:" a bit further down in the docs.

This should do what you want:

```python
from windrose import WindroseAxes
import numpy as np

ws = np.random.random(500) * 6
wd = np.random.random(500) * 360

ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white', nsector=36)
ax.set_legend()
```

I don't think it's easy to read though - 16 is the sweetspot imo.

![grafik](https://github.com/python-windrose/windrose/assets/54631600/04bb77c9-8caa-452e-ad91-b8596d2a9aec)

**Comment by vimalaathythan-v2w** [comment]
Hi ,

Thanks for the quick and helpful response. Setting nsector=36 works perfectly! I'll keep your readability tip about 16 in mind.

Much appreciated!

Thanks & Regards,
Vimalaathythan M.
+91 7604832944

V2W Software Solutions Pvt. Ltd.

Empowering Rural India

Confidentiality Note: The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so we can ensure such an error does not occur.
________________________________

**Comment by vimalaathythan-v2w** [comment]
***@***.*** would like to recall the message, "Re: [python-windrose/windrose] custom binning of wind direction direction (Issue #273)".
