### ISSUE TITLE
unify doc pages

### ISSUE THREAD

**Issue by jkittner** [python-windrose/windrose#277]
One thing where multiple people ran into is, that there are two different pages for docs.
- The old one: https://windrose.readthedocs.io/en/latest/index.html
- The new one: https://python-windrose.github.io/windrose/

The old docs are not updated any longer and are not quite correct any more. I think that's a bit misleading when getting started.

@ocefpaf, you also probably have no access to rtd, right? It would be great to at least add a note there, or fully remove it (that would likely break a lot of links). I don't know a lot about rtd, but you probably can't set up a redirect for the "latest" docs, right?

I'm not sure how to solve this. Google also only spits out the old docs...

**Comment by scls19fr** [comment]
I've just delete RTD Windrose page. I hope that it will help to avoid users confusion.

**Comment by jkittner** [comment]
Nice, I hope google will catch up soon!
