### ISSUE TITLE
How to change the text of legend

### ISSUE THREAD

**Issue by NUISTjason** [python-windrose/windrose#281]
I want to change the label text of ax.bar to 'JAN', 'FEB', 'MAR', but neither set the label parameter in ax.bar nor set the labels parameter in ax.set_legend works. What should I do?
```python
ax = WindroseAxes.from_ax()
ax.bar(np.concatenate(mwd_season), np.concatenate(mws_season), normed=True, opening=0.8, 
       edgecolor='white', bins=np.arange(1, 4, 1))
ax.set_legend(labels=['JAN', 'FEB', 'MAR']) # It doesn't work
ax.set_title('Wave Direction Distribution')
ax.set_xlabel('Wind Direction (Degrees)')
ax.set_ylabel('Frequency')
plt.show()
```
![output](https://github.com/user-attachments/assets/b1f24758-a223-4e60-977a-c5c1554d0fd6)

**Comment by jkittner** [comment]
Are you sure a windrose is what you want?

The only way to include a temporal dimension is by having subplots - in your case for each month.

Maybe have a look at this section of the docs: https://python-windrose.github.io/windrose/usage-output.html#Subplots

Also I don't think you want Frequency as a y-label - If you really need a label, maybe set a legend title or _maybe_ the theta axis?

**Comment by NUISTjason** [comment]
I would like to use Windrose to display the wave direction distribution for each month,  so I use the month instead of speed. So I want to change the legend text to the month. Do you mean that this approach is not reasonable?

**Comment by NUISTjason** [comment]
I tried to draw the wave direction for each month separately, and using the month instead of speed is indeed incorrect. Thank you for your reply.

**Comment by ocefpaf** [comment]
Closing this as solved. Please re-open if you disagree.
