### ISSUE TITLE
Is it possible to add other objects on top of the windrose?

### ISSUE THREAD

**Issue by Data-drone** [python-windrose/windrose#31]
I want to shade in particular slices of the windrose to show where certain buildings are relative to the windrose profile

**Comment by scls19fr** [comment]
I've never done this. So I can't tell. An other approach could be to export windrose as png (with transparent background being blank) and import this drawing into your building drawing software.
http://stackoverflow.com/questions/15857647/how-to-export-plots-from-matplotlib-with-transparent-background

**Comment by ocefpaf** [comment]
@Data-drone I guess one could get the `ax` and plot the marker using the polar coords. Closing this b/c it is a usage question and not something the devs can act upon but let us know if you figure this one out!
