### ISSUE TITLE
What is the default colormap for windrose?

### ISSUE THREAD

**Issue by cqcn1991** [python-windrose/windrose#35]
This is the plot I get using `windrose`,

![qq](https://cloud.githubusercontent.com/assets/2425141/16772605/79347e08-4887-11e6-81c4-43368e3c93d0.png)

I notice that in https://github.com/scls19fr/windrose/blob/a024d3af097c69d28f98328e7eb2b3dbc215838a/windrose/windrose.py , there is not `cmap` for `bar`. Then I want to know, how to change the colormap of it?

Addtionally, is it `jet`? Will it be changed according to `Matplotlib` update? (http://matplotlib.org/style_changes.html)

**Comment by scls19fr** [comment]
Hi @cqcn1991 

I'm really impressed by [your work](https://github.com/cqcn1991/Wind-Speed-Analysis) !

Sorry but I don't know what it will happen with Matplotlib update...

If no cmap argument is passed it might be `jet`
https://github.com/scls19fr/windrose/blob/a024d3af097c69d28f98328e7eb2b3dbc215838a/windrose/windrose.py#L243


You might try to pass cmap argument (different than jet) to both `bar` and `windrose`
if only windrose take account of this cmap argument... than a PR to fix will be very nice

**Comment by cqcn1991** [comment]
Just tried it 

```
# Not work
ax.bar(df.dir_windrose, df.speed, normed=True, opening=0.8, edgecolor='white', nsector=36, cmap='viridis')
# Works
viridis = plt.get_cmap('viridis')
ax.bar(df.dir_windrose, df.speed, normed=True, opening=0.8, edgecolor='white', nsector=36, cmap=viridis)
```

From https://github.com/scls19fr/windrose/blob/a024d3af097c69d28f98328e7eb2b3dbc215838a/windrose/windrose.py#L242 , I can see that it's not `string` name but the `cmap` itself get passed. Not sure if this is a good design.

I find the `cmap=plt.get_cmap(name)` from http://matplotlib.org/examples/color/colormaps_reference.html

**Comment by scls19fr** [comment]
I think it's better to pass `cmap` itself and not its name because you can be able to pass a custom cmap (a user defined cmap that don't have name) this way.

**Comment by cqcn1991** [comment]
@scls19fr OK. I post this issue is because I just know that `matplotlib` is changing from `jet` to `viridis`, and I think you maybe interested in it as well. If you are unfamiliar with this, you can see discussion here (http://matplotlib.org/style_changes.html) and here (http://stats.stackexchange.com/questions/223315/why-use-colormap-viridis-over-jet).

Addtionally, thanks for your intereste in https://github.com/cqcn1991/Wind-Speed-Analysis, could you tell me where intereste you most? Honestly, while I open-sourced this project (It's my Master Thesis, and I'm working a paper on it), I never know any other people would care about it.
