### ISSUE TITLE
Cannot Import Name poly_between

### ISSUE THREAD

**Issue by dennydengler** [python-windrose/windrose#37]
![error 2](https://cloud.githubusercontent.com/assets/20861100/17439762/94258f2c-5af7-11e6-9cf5-afa3bfe106ab.jpg)
![error 3](https://cloud.githubusercontent.com/assets/20861100/17439765/9b878838-5af7-11e6-99fd-8c4a380507df.jpg)
So I am using python 3.5. When I tried to import windrose, it says that it cannot import name 'poly_between'. Then I tried upgrading matplotlib but then it says that lapack isn't found. 
Then I came back to check and saw that windrose is only built for up to python 3.4. Would a windrose package from python 3.5 be coming out soon?
Thank you.

**Comment by scls19fr** [comment]
I don't think it's a windrose issue.
What distribution of Python are you using ?
I suggest using a scientific distribution of Python such as Anaconda Python https://www.continuum.io/downloads

**Comment by dennydengler** [comment]
Hi, scls19fr, thank you for your input.
Hmm if memory serves me right, I got it from here:
https://www.python.org/downloads/
I wouldn't know what distribution that is though.
Also concerning the use of Anaconda, my primary concern is the incompatibility between that and pip install, but what do you think?

**Comment by scls19fr** [comment]
With Anaconda you will have `pip` but also `conda`
http://conda.pydata.org/docs/intro.html

I suggest 
- reading http://stackoverflow.com/questions/6719309/python-distributions-and-environments-for-scientific-computing
- Uninstalling your current Python
- installing a scientific Python distribution which come with all useful libraries for scientific work

**Comment by scls19fr** [comment]
@dennydengler are you still facing this problem ?

**Comment by pooranasaviour** [comment]
Hallo, I have the same problem. Here are the last lines from the error message:
'ImportError: cannot import name 'poly_between' from 'pylab' (C:\ProgramData\Anaconda3\lib\site-packages\pylab.py)'
I am using python 3.7.1 (Anaconda)

**Comment by scls19fr** [comment]
You should uninstall windrose...

Try it's correctly uninstalled (`import windrose` should fail)

Then install latest development version

https://github.com/python-windrose/windrose#install-latest-development-version
