### ISSUE TITLE
WindroseAxes from existing ax

### ISSUE THREAD

**Issue by julietbravo** [python-windrose/windrose#41]
Perhaps I'm missing something, but your example:

```
ax = WindroseAxes.from_ax()
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
```

works perfectly, until I try to create a `WindroseAxes` from an existing ax. For example:

```
ax1 = pl.subplot(211)
ax2 = WindroseAxes.from_ax(ax1)
ax2.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
```

fails at `ax2.bar` (`Unknown property normed`), because `ax2` is now no longer a `windrose.WindroseAxes` but a `matplotlib.axes._subplots.AxesSubplot`, as `from_ax` simply returns the given `axes` if it is not equal to `None`.

Is it somehow possible to add multiple wind roses to a figure, from existing `axes`?

**Comment by scls19fr** [comment]
Maybe you might have a look at https://github.com/scls19fr/windrose/issues/20#issuecomment-239762028

**Comment by kthyng** [comment]
> Maybe you might have a look at https://github.com/scls19fr/windrose/issues/20#issuecomment-239762028

It looks like this should now link here instead: https://github.com/python-windrose/windrose/issues/20

**Comment by weber-s** [comment]
Indeed, I close this issue. https://github.com/python-windrose/windrose/issues/20#issuecomment-239762028
