### ISSUE TITLE
Smooth plot

### ISSUE THREAD

**Issue by georgebv** [python-windrose/windrose#43]
I have found some real dark magic. Your module plots roses as triangles emerging from center - with straight, blocky edges. However, if you add this code (i.e. any histogram with pyplot)
 `plt.hist([0, 1]); plt.close()`
 before executing your function (i.e. WindroseAxes), you get smooth curvy roses like here:
http://climate.ncsu.edu/windrose.php
![krdu_windrose](https://cloud.githubusercontent.com/assets/22249152/19096455/8535c3e0-8a6a-11e6-9273-718bf5e51ed8.png)
This doesn't make any sense and I couldn't figure out why this works, but it does. Any idea on why this happens and if you can add this "feature" to your module?

**Comment by scls19fr** [comment]
Hello @georgebv ,

Please, could you provide sample data (or random data), full code and screenshots comparing these 2 behaviors ?

Kind regards

**Comment by georgebv** [comment]
This is the regular rose plot (vanilla):
![rose](https://cloud.githubusercontent.com/assets/22249152/19112656/0a6ee85c-8ad4-11e6-8c15-406f31ae6314.png)
This is what happens when I add and remove a pyplot histogram before your function:
![rose](https://cloud.githubusercontent.com/assets/22249152/19112674/3277d8fe-8ad4-11e6-9e9f-6c8fc5a7fe6e.png)


This is my code:

def rose_plot(df, **kwargs):
    Plots rose of values *val* for directions *direction*
    in dtaframe *df* and saves it to folder *savepath*.

    Parameters
    ----------
    df : pandas dataframe
        Pandas dataframe with columns *val* and *direction*
    val : string
        Column name of values in dataframe *df* (i.e. 'Hs')
    direction : string
        Column name of directions in dataframe *df* (i.e. 'Dp)
    valbins : int
        Number or value bins (default = 6)
    dirbins : int
        Number of directional bins (default = 12)
    savepath : string
        Path to output folder (default = doesn't save) (i.e. 'C:\\folder')
    savename : string
        Name of file
    startfromzero : bool
        Indicates if plot starts from 0 (N) (default = False)
    valbinsize : float
        Set binsize to override *valbins* parameter (default = None, assigns bins automatically)
    title : str
        Plot title
    
    direction = kwargs.get('direction', 'Dp')
    val = kwargs.get('val', 'Hs')
    valbins = kwargs.get('valbins', 6)
    dirbins = kwargs.get('dirbins', 12)
    savepath = kwargs.get('savepath', None)
    savename = kwargs.get('savename', 'Rose')
    title = kwargs.get('title', 'Rose')
    legend = kwargs.get('legend', 'Value [unit]')
    startfromzero = kwargs.get('startfromzero', False)
    valbinsize = kwargs.get('valbinsize', None)

    plt.hist([0, 1])
    plt.close()
    a = df[pd.notnull(df[val])]
    a = a[pd.notnull(a[direction])]
    if startfromzero:
        a[direction] = a[direction].apply(lambda x: x - 0.5 * 360 / dirbins)
    ax = windrose.WindroseAxes.from_ax()
    if valbinsize is not None:
        valbins = np.arange(0, a[val].max() + valbinsize, valbinsize)
    ax.bar(
        a[direction],
        a[val],
        normed=True,
        opening=1,
        edgecolor='black',
        bins=valbins,
        nsector=dirbins,
        cmap=cm.jet,
        startfromzero=startfromzero
    )
    ax.set_legend()
    ax.legend(loc=(-0.12, 0.75), title=legend, fontsize=9)
    ax.get_legend().get_title().set_fontsize('9')
    plt.title(title, y=1.08, fontsize=16)
    if savepath is not None:
        plt.savefig(savepath + '\\' + savename + '.png')
        plt.close()

**Comment by scls19fr** [comment]
Oh yes I see it now clearly!

![capture d ecran 2016-10-05 a 14 33 40](https://cloud.githubusercontent.com/assets/109167/19113203/dbd1c458-8b08-11e6-89df-70c0f03adbde.png)

is better than

![capture d ecran 2016-10-05 a 14 33 05](https://cloud.githubusercontent.com/assets/109167/19113196/d23bb6c4-8b08-11e6-8a14-a7ac2a5148d8.png)

Any idea @LionelR ?


PR is welcome!

**Comment by scls19fr** [comment]
Pinging @wanglongqi

**Comment by wanglongqi** [comment]
@scls19fr Any idea about what is happening here? calling `bar` function also changes the behavior.

**Comment by scls19fr** [comment]
Sorry @wanglongqi I haven't been able to understand what is happening.

**Comment by scls19fr** [comment]
Any help on this is welcome

**Comment by wanglongqi** [comment]
@scls19fr I think this is a bug in upstream, i.e. matplotlib. Probably should fire an issue in matplotlib repository.

**Comment by LionelR** [comment]
Maybe passing the transform parameter to the plots methods calls can solve this problem. See https://stackoverflow.com/questions/19827792/matplotlib-drawing-a-smooth-circle-in-a-polar-plot

**Comment by tacaswell** [comment]
Likely related, with matplotlib 2.0 and windrose 1.6 the contour example from the front page has straight lines on the contours, but round edges on the fill

![so](https://user-images.githubusercontent.com/199813/28603294-46890a58-7191-11e7-8ee8-03a41cdcff46.png)
