### ISSUE TITLE
Can you add an argument to add units to the legend

### ISSUE THREAD

**Issue by blaylockbk** [python-windrose/windrose#56]
presently, the legend displays just the numbers, e.g. [0.0 : 5.0]

It would be nice if we could specify the units with a simple string argument
```python
ax.set_legend(units="mph")
```
would set legend label as [0.0 : 5.0] mph

or 
```python
ax.set_legend(units="m/s")
```
would set legend label as [0.0 : 5.0] m/s

**Comment by scls19fr** [comment]
Hello @blaylockbk 

Nice idea
PR are welcome

See
https://github.com/python-windrose/windrose/blob/master/windrose/windrose.py#L181

Kind regards

**Comment by mwheels** [comment]
PR: #128
