### ISSUE TITLE
Handling "Calms"

### ISSUE THREAD

**Issue by mccannjb** [python-windrose/windrose#58]
Is there a way to treat 'calms' differently within datasets?  For example, in the dataset I'm attempting to create windroses for, calms are denoted as Wd=0.0 and Ws=0.0 (whereas North winds are denoted as Wd=360.0).  It seems like in this case they are currently lumped in with North winds.

**Comment by scls19fr** [comment]
Maybe you should simply remove these data from your input data for example using a Pandas DataFrame and boolean indexing

    df = df[df["Ws"] > 0.1]

**Comment by mccannjb** [comment]
I have started removing the calms from the dataframes prior to passing to the windrose bar function similar to the way you suggested.  What I was hoping is that there is some way to replicate the typical calms representation within other windroses (i.e. a circle in the center, from which the sector "petals" emanate) as the example below shows:
![samplewindrose](https://cloud.githubusercontent.com/assets/2846154/26323823/5be64426-3efe-11e7-89ac-52d600921241.png)

**Comment by scls19fr** [comment]
Pinging @LionelR

**Comment by LionelR** [comment]
It should be possible to compute the calms frequency in the histogram method and initialise the offset plots methods variable accordingly after drawing a centered circle. I don't have a computer right now but I can try something tomorrow if you can't in the mean time.

**Comment by goharShoukat** [comment]
Hi @LionelR ! 
Was this functionality added to the library? If not, can you explain your last comment please? I used the ax.set_rorigin to get offset but this is just offsetting the whole scale. It doesnt give me a region for calm representation

**Comment by goharShoukat** [comment]
I found a way to get around this. Its not the most elegant solution, but it works. The pyplot.text() allows us to place text at a coordinate of our choosing. And you can get this nice circle smack in the middle of the polar plot. Here is the sample code:
`plt.text(0., 0., "Calm", size=18,
         ha="center", va="center",
         bbox=dict(boxstyle="circle")
         )`

**Comment by ocefpaf** [comment]
This was implemented in https://github.com/python-windrose/windrose/pull/102
