### ISSUE TITLE
Merge with other projects

### ISSUE THREAD

**Issue by scls19fr** [python-windrose/windrose#6]
See other projects to provide most of their features
- https://github.com/arifwn/thorn
  - thorn.py provides a PyQt application
- https://github.com/aladagemre/windrose-drawer
  - provide a command line interface to display wind rose from CSV or XLS or XLSX data

**Comment by ocefpaf** [comment]
These projects are 8 and 10 years old. If they are updated I would suggest they depend on the windrose PyPI package instead.

@scls19fr can we close this one?
