### ISSUE TITLE
Inconsistent licence files

### ISSUE THREAD

**Issue by scls19fr** [python-windrose/windrose#65]
Following https://github.com/openjournals/joss-reviews/issues/268#issuecomment-318916583

In 
https://github.com/python-windrose/windrose/blob/master/setup.py
it's `License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)'`

but in https://github.com/python-windrose/windrose/blob/master/LICENCE
and in https://github.com/python-windrose/windrose/blob/master/windrose/version.py#L5
it's CeCILL-B

In https://pypi.python.org/pypi?%3Aaction=list_classifiers
CeCILL-2.1 is the only CeCILL license (moreover it's OSI approved)
so if we change to use CeCILL-B everywhere in this project we need to know what should be written in `setup.py` (maybe only its [SPDX](https://en.wikipedia.org/wiki/SPDX): `CeCILL-B`)

@LionelR Should we update update `setup.py` or `LICENSE` (and `version.py`)?

I noticed that some other projects have same "problem".
https://www.google.fr/search?q=Cecill-b+python+setup.py
https://github.com/d9pouces/django-floor
https://github.com/akaszynski/PyACVD
...

CeCILL-2.1 is a GPL compatible french license
CeCILL-B License is a BSD compatible french license (GPL incompatible)

https://fr.wikipedia.org/wiki/Licence_CeCILL

CeCILL-B imposes author(s) citation not CeCILL-2.1

**Comment by scls19fr** [comment]
Original version from http://youarealegend.blogspot.com/search/label/windrose was CeCILL-B. 
I did a mistake when I created `setup.py` and this repository. I put the only CeCILL license available 
in https://pypi.python.org/pypi?%3Aaction=list_classifiers which was CeCILL-2.1

**Comment by LionelR** [comment]
@scls19fr please keep the CeCILL-B license wherever it's necessary

**Comment by scls19fr** [comment]
Ok I will do
I will probably need to retag

**Comment by scls19fr** [comment]
Fixed but according both https://spdx.org/licenses/ and https://opensource.org/licenses/alphabetical CeCILL-B is not listed in OSI approved list of license (despite the fact that http://www.cecill.info/licences.en.html claims that it has the caracteristics of BSD-like licenses)
I just hope it won't be an issue for Journal of Open Source Software review.

**Comment by scls19fr** [comment]
Reopening this issue because of pip upload fail!

```
Submitting dist/windrose-1.6.2.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): classifiers: 'License :: CEA CNRS Inria Logiciel Libre License B (CeCILL-B)' is not a valid choice for this field
error: Upload failed (400): classifiers: 'License :: CEA CNRS Inria Logiciel Libre License B (CeCILL-B)' is not a valid choice for this field```

**Comment by scls19fr** [comment]
I also tried

```
    classifiers=[
        # Pick your license as you wish (should match "license" above)
        'CeCILL-B',
    ],
```

and


```
    classifiers=[
        'License :: CeCILL-B',
    ],
```

and get similar error

`Upload failed (400): classifiers: 'License :: CeCILL-B' is not a valid choice for this field`

**Comment by scls19fr** [comment]
I've just opened an issue on PyPi https://github.com/pypa/pypi-legacy/issues/679 to ask to add CeCILL-B to allowed classifiers in setup.py or to provide a better workaround.

**Comment by LionelR** [comment]
@scls19fr for consistency with the primary license and to be simple in the process, I think we can use the MIT license as a substitute.

**Comment by scls19fr** [comment]
I pushed code to PyPi without defining License in classifier (as suggested in https://github.com/pypa/pypi-legacy/issues/679 )
License is defined to CeCILL-B in this release.
If that's an issue for JOSS I will create an other release with dual license.
