### ISSUE TITLE
Weibull plot pdf fit not as expected

### ISSUE THREAD

**Issue by daniclaar** [python-windrose/windrose#74]
First of all, thanks for making this open source!  
  
I am following the code from the readme to create a windrose for my dataset (wave height and direction). I have been able to successfully create a windrose for this dataset, but when I try to fit a Weibull distribution, it doesn't appear to fit correctly. Here is my code:  

```
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np
import pandas

from windrose import WindAxes  
ax = WindAxes.from_ax()  
bins = np.arange(0, 4 + 1, 0.25)  
bins = bins[1:]  
ax, params = ax.pdf(hs, bins=bins)  
plt.show()
```
And here is what the data looks like:  
```
hs # I am using this for wave height, rather than wind speed
array([ 0.      ,  0.07    ,  0.46    , ...,  1.859375,  1.84375 ,  1.84375 ]) # Looks like this
```  
And this is what the resulting figure looks like:  
![weibull_waverose](https://user-images.githubusercontent.com/5808230/36992709-a3290690-2060-11e8-89b1-c2a8502e067d.PNG)  
  
Can you help me figure out why the histogram appears to be plotting correctly, but the pdf fit looks so incorrect?  
Thank you very much in advance, and thanks for making such a great tool!

**Comment by daniclaar** [comment]
Apologies, I just realized I have a single zero at the beginning of my dataset (should have noticed that above!), and fitting a Weibull distribution breaks if there are any zeros in the data.

**Comment by scls19fr** [comment]
No problem.
My pleasure.
