### ISSUE TITLE
Simulated Wind for animated plots

### ISSUE THREAD

**Issue by ruffsl** [python-windrose/windrose#75]
This is perhaps an odd question, but would folks here know of a good way to simulate wind readings that would be realistic. 

I'm thinking of high sample rates in time where the direction and speed are more continuous in nature, as angle or intensity is not probable to change by large degree instantaneously. Almost as direction and speed could be thought of as variables in a dynamic equation. I'd like to synthesize results that look like this:
https://youtu.be/3CWpjSEt0so

perhaps there is another python module that would be appropriate.

**Comment by ocefpaf** [comment]
This is beyond the scope of the library but an interesting question. Hope you found a solution somewhere. Closing it for now due to inactivity.
