### ISSUE TITLE
Map overlay

### ISSUE THREAD

**Issue by scls19fr** [python-windrose/windrose#87]
Some users of Python windrose could be interested by such a feature.

https://github.com/python-windrose/windrose/issues/54#issuecomment-388326349
https://github.com/python-windrose/windrose/issues/54#issuecomment-388410884

**Comment by weber-s** [comment]
It is now possible with v1.6.8, and documented here:  https://windrose.readthedocs.io/en/latest/usage.html#overlay-of-a-map 

Do we wan't a full built-in integration of this in windrose?  Right now, it's work thanks of a bit of matplotlib tweaking.

**Comment by ocefpaf** [comment]
For the sake of flexibility I don't think windrose should provide a built-on method for that. Matplotlib inset is probably the way to go, so folks can use it with any mapping library they choose. While clunky, it is flexible, robust, and mpl is constantly improving on it.

@scls19fr and @weber-s  what do you think? If you agree can we close this one?

**Comment by weber-s** [comment]
Indeed, to me a detail example in the doc is enough.

**Comment by ocefpaf** [comment]
@scls19fr doing some housekeeping and closing this one. Please re-open if you disagree.
