### ISSUE TITLE
README is not rendered correctly on pypi

### ISSUE THREAD

**Issue by scls19fr** [python-windrose/windrose#98]
Hello,

README is not rendered correctly on pypi
See https://pypi.org/project/windrose/

I thought pypi was supporting now Markdown?
https://github.com/pypa/warehouse/issues/869

Any idea what is going wrong?

Kind regards

**Comment by ocefpaf** [comment]
I know of [some issues](https://github.com/pypa/warehouse/issues?q=is%3Aissue+sort%3Aupdated-desc+markdown+is%3Aclosed) with `warehouse` and I'll try to debug this later. (I had one in my project where just updating twine solved it.)
