### ISSUE TITLE
Wrong angle in scatter

### ISSUE THREAD

**Issue by StSav012** [python-windrose/windrose#99]
All the polar plots have 0 angle at North, but `wrscatter` is drawn like a usual polar plot: the angle is counted from East anti-clockwise. It confuses.
The version is the latest by the date, 1.6.4.

**Comment by scls19fr** [comment]
Thanks @StSav012 for reporting this. However, a Minimum Working Example showing this (with fake data) will be nice.

**Comment by StSav012** [comment]
Here you are.
```python
import windrose
import matplotlib.pyplot as plt
windrose.wrscatter([0], [1])
# plt.annotate('zero angle', (0, 1), xytext=(-8, 8), textcoords='offset points')
plt.show()
```

**Comment by scls19fr** [comment]
Could you try fixing code and submit a pull request?

Maybe adding 

```python
vf = np.vectorize(lambda x: x + np.pi / 2)
direction = vf(direction)
```

before

https://github.com/python-windrose/windrose/blob/a93c9225af737526b5d9a7200cabdfe660079043/windrose/windrose.py#L738

**Comment by StSav012** [comment]
No, the direction would then be wrong.
MWE:
```python
import numpy as np
import windrose
import matplotlib.pyplot as plt
wd = np.radians([0, 45, 90])
ws = [1, 0.5, 1.5]
windrose.wrscatter(wd, ws)   # N, NE, and E
plt.annotate('N', (0, 1), xytext=(-8, 8), textcoords='offset points')
plt.annotate('NE', (np.radians(45), 0.5), xytext=(8, -8), textcoords='offset points')
plt.annotate('E', (np.radians(90), 1.5), xytext=(8, 0), textcoords='offset points')
plt.show()
```

I used `direction = -np.array(direction) + np.radians(90)`. Not sure whether I should explicitly convert `direction` into a `numpy` array, or it already is an array. I'd rather do
```python
direction = -(direction if isinstance(direction, np.ndarray) else np.array(direction)) + np.radians(90)
```

By the way, [`numpy.vectorize`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html) is not for speed but just for convenience, as they keep reminding at [SO](https://stackoverflow.com/questions/35215161/most-efficient-way-to-map-function-over-numpy-array).

**Comment by scls19fr** [comment]
You are right about sign... (and annotate help a lot to see it):

    vf = np.vectorize(lambda x: -x + np.pi / 2)

Not sure that speed is something we should really care for now.

What is really important is that we can support Python list and Numpy array as input.

Maybe `vf = np.vectorize(lambda wd: -wd + np.pi / 2)` can be defined as global ie outside of `wrscatter` function so it could decrease timing cost of vectorizing function.

```python
import numpy as np
import windrose
import matplotlib.pyplot as plt
wd = np.radians([0, 45, 90, 135, 180, 225, 270, 315])
ws = [1.0, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
vf = np.vectorize(lambda wd: -wd + np.pi / 2)
wd = vf(wd)
windrose.wrscatter(wd, ws)   # N, NE, and E
plt.annotate('N', (0, 1), xytext=(-8, 8), textcoords='offset points')
plt.annotate('NE', (np.radians(45), 0.5), xytext=(8, -8), textcoords='offset points')
plt.annotate('E', (np.radians(90), 1.5), xytext=(8, 0), textcoords='offset points')
plt.show()
```

**Comment by StSav012** [comment]
Right then. I used to plot some 10,000 to 1,000,000 points in scatter as well, so I have to care about speed. Anyway, I have nothing left to suggest. Feel free to close the issue when you submit a correction. Thanks!

**Comment by scls19fr** [comment]
Could you try removing windrose and installing latest master version?

**Comment by StSav012** [comment]
Looks fine except for some 30 times decreased performance comparing to my method.
```python
import numpy as np
from matplotlib import pyplot as plt
from time import perf_counter as pc

VF = np.vectorize(lambda wd: -wd + np.pi / 2)
stsav012_correction_method_time = []
scls19fr_correction_method_time = []

ns = 10 ** np.arange(0, 8)
for n in ns:
    wd = np.random.random(n) * 2. * np.pi

    start_time = pc()
    wd = -np.array(wd) + np.radians(90)
    end_time = pc()
    stsav012_correction_method_time.append(end_time - start_time)

    start_time = pc()
    wd = VF(wd)
    end_time = pc()
    scls19fr_correction_method_time.append(end_time - start_time)

plt.loglog(ns, stsav012_correction_method_time, label="StSav012's method")
plt.loglog(ns, scls19fr_correction_method_time, label="scls19fr's method")
plt.xlabel('number of points')
plt.ylabel('time consumption [s]')
plt.legend()
plt.show()
```
Needless to say that `np.vectorize` consumes much, much more memory. Tested with [memusg](https://gist.github.com/netj/526585): your method takes up to 803204 kiloBytes against 183840 kiloBytes of mine. I ran out of both memory and swap trying to calculate the `np.vectorize` time consumption for `n = 10 ** 8`.
Code 0:
```python
import numpy as np
VF = np.vectorize(lambda wd: -wd + np.pi / 2)
n = 10 ** 7
wd = np.random.random(n) * 2. * np.pi
wd = VF(wd)
```
Code 1:
```python
import numpy as np
n = 10 ** 7
wd = np.random.random(n) * 2. * np.pi
wd = -np.array(wd) + np.radians(90)
```

**Comment by scls19fr** [comment]
Could you try it again @StSav012 ?

**Comment by StSav012** [comment]
Now it looks fine to me. At least, a have nothing else to suggest.
